## Training a classification model

In [1]:
import pandas as pd
import os
import sys
sys.path.insert(0, "../")

from src.training_models.classification_models import ClassificationModel
from sklearn.model_selection import train_test_split

### Load generated dataset

In [2]:
type_encoder = "embedding"
encoder = "onehot"
df_data = pd.read_csv(f"../results/encoders/{type_encoder}/{encoder}/coded_dataset.csv")
df_data.head(5)

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_12,p_13,p_14,p_15,p_16,p_17,p_18,p_19,p_20,monomer_state
0,0.037815,0.008403,0.07563,0.067227,0.050420,0.092437,0.042017,0.054622,0.084034,0.075630,...,0.042017,0.033613,0.02521,0.046218,0.058824,0.067227,0.004202,0.0,0.050420,0
1,0.033613,0.012605,0.07563,0.067227,0.050420,0.092437,0.042017,0.054622,0.084034,0.075630,...,0.042017,0.033613,0.02521,0.046218,0.058824,0.067227,0.004202,0.0,0.050420,0
2,0.033613,0.008403,0.07563,0.067227,0.050420,0.092437,0.042017,0.054622,0.084034,0.079832,...,0.042017,0.033613,0.02521,0.046218,0.058824,0.067227,0.004202,0.0,0.050420,0
3,0.033613,0.008403,0.07563,0.067227,0.050420,0.092437,0.042017,0.054622,0.084034,0.075630,...,0.042017,0.033613,0.02521,0.046218,0.063025,0.067227,0.004202,0.0,0.050420,0
4,0.033613,0.008403,0.07563,0.067227,0.054622,0.092437,0.042017,0.054622,0.084034,0.075630,...,0.042017,0.033613,0.02521,0.050420,0.058824,0.067227,0.004202,0.0,0.046218,0

In [3]:
responses = df_data["monomer_state"].values
df_data = df_data.drop(columns=["monomer_state"])

In [4]:
train_data, validation_data, train_response, validation_response = train_test_split(df_data, responses, random_state=42, test_size=.30)

### Training model

In [5]:
folder_export = f"../results/performance/{type_encoder}/{encoder}"
os.makedirs(folder_export, exist_ok=True)
name_export = f"{folder_export}/results_exploration.csv"

model_instance = ClassificationModel(
    train_values = train_data,
    train_response = train_response,
    test_values = validation_data,
    test_response = validation_response
)

df_exploration = model_instance.apply_exploring()
df_exploration.to_csv(name_export, index=False)